# Generated by Django 4.1.5 on 2023-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
