# Generated by Django 3.2.10 on 2023-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_productdb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
