# Generated by Django 3.2.10 on 2023-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('CardName', models.CharField(blank=True, max_length=50, null=True)),
                ('CreditNo', models.IntegerField(blank=True, null=True)),
                ('Expiration', models.DateField(blank=True, max_length=100, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
