# Generated by Django 4.1.3 on 2023-02-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='Confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
