# Generated by Django 4.1.3 on 2023-02-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_customerdb_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='Expiration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
